#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y
sudo apt-get install -y nginx
mkdir -p /etc/nginx/html
echo 'Hello World!'  > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
