#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update -y --fix-missing &&
sudo apt-get install -y nginx &&
sudo ufw allow 'Nginx HTTP' &&
echo "Hello World!" > index.html &&
sudo chmod 755 index.html &&
sudo cp index.html /var/www/html/ &&
sudo rm -f index.html
