#!/usr/bin/env bash
sudo apt update -y
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get install -y haproxy=2.6.\*
sudo chown -R "$USER":"$USER" /etc/haproxy/
printf "frontend bnb-frontend
        bind *:80
        mode http
        default_backend bnb-backend
backend bnb-backend
        balance roundrobin
        server web-01 18.206.232.147 check port 80
        server web-02 54.173.168.47 check port 80
" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start
