#!/usr/bin/env bash
# script that loops from 1 to 20 and:


i=0
while [ $i -lt 20 ];
do
    case $i in
    3)
        echo "bad luck from China"
    ;;
    8)
        echo "bad luck from Japan"
    ;;
    16)
        echo "bad luck from Italy"
    ;;
    *)
        echo `expr $i + 1`
    ;;
    esac
    ((i++))
done
