#!/usr/bin/env bash
# Configures a sudo ufw firewall to block all incoming traffic
# except for ports 22 ssh, 443http ssl and 80.http

sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
